org: danielomunoz
app: deale-app
service: deale-app
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
          - dynamodb:*
      Resource:
          - arn:aws:dynamodb:eu-west-1:900750044523:table/favouriteOrganizationTable
  apiGateway:
    apiKeys:
      - name: 'FirstApiKey'
        value: 'abcdefghijklmnopqrstuvwxyz1234567890'

functions:
  getFavouriteOrganization:
    handler: favouriteOrganization_handler.getAllFavouritesOrganizations
    events:
      - http:
          path: /favouriteOrganization
          method: get
          private: true
  postFavouriteOrganization:
    handler: favouriteOrganization_handler.postFavouriteOrganization
    events:
      - http:
          path: /favouriteOrganization
          method: post
          private: true

resources:
  Resources:
    favouriteOrganizationTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: favouriteOrganizationTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1